---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: samba-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: samba-test
    spec:
      containers:
        - command:
            - /sbin/tini
            - --
            - /usr/bin/samba.sh
            - -p
            - -u
            - user;pass
            - -s
            - share;/export;no;no;no;user
            - -p
            - -S
          image: dperson/samba
          imagePullPolicy: Always
          name: samba-test
          ports:
            - containerPort: 139
              protocol: TCP
            - containerPort: 445
              protocol: TCP
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: samba-test
spec:
  type: ClusterIP
  ports:
    - port: 445
      targetPort: 445
      protocol: TCP
      name: smb
    - port: 139
      targetPort: 139
      protocol: TCP
      name: smblegacy
  selector:
    app.kubernetes.io/name: samba-test