kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-nodeplugin-smbplugin
spec:
  template:
    spec:
      containers:
        - name: smb
          command:
            - "/app/main"
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"